version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: nlp
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stem_careers

    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nlp -d stem_careers"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - DATABASE_URL=postgresql://${POSTGRES_USER:-nlp}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-stem_careers}

volumes:
  postgres_data: 